### ISSUE TITLE
I'm unsure of how to actually use this to FUD an executable?

### ISSUE THREAD

**Issue by pssolanki111** [GetRektBoy724/BetterXencrypt#3]
Hi there,

Thanks for the excellent tool : )

Here is my use case. I have an executable (it's a `RAT`). 
Now I'm unsure of how to use the tool to `FUD` the executable.

Do I specify the `./path/to/file.exe` inside `--infile` or how does that work? is that even possible?

**Comment by GetRektBoy724** [comment]
Im so sorry m8,this crypter is only for powershell scripts and payload 😅

**Comment by pssolanki111** [comment]
Hey Thanks for getting back. And Not a problem : )

Thanks for the tool btw : )

**Comment by GetRektBoy724** [comment]
> Hey Thanks for getting back. And Not a problem : )
> 
> Thanks for the tool btw : )

yeah np
