### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Maruf497** [GetRektBoy724/BetterXencrypt#7]
![Screenshot 2021-12-28 130543](https://user-images.githubusercontent.com/72127671/147538327-418dccb0-ab72-4ab1-b04a-d83410e33704.png)
Can you make tutorials on how to encrypt 1 file without getting any error. I am new to powershell and keep getting this error

**Comment by GetRektBoy724** [comment]
What you ran is not BetterXencrypt, you downloaded something wrong

**Comment by Maruf497** [comment]
Thanks for the reply. I resolved the issue and working great now❤️❤️❤️
