### ISSUE TITLE
dude is this crypter working ??

### ISSUE THREAD

**Issue by FOOODU** [GetRektBoy724/BetterXencrypt#9]
is crypter still working and able to bypass av detection ??

**Comment by GetRektBoy724** [comment]
Probably not, to be honest. I've been released this crypter for a while now and im pretty sure the stub has been sigged by AVs.

**Comment by chainski** [comment]
Try [AesEncoder](https://github.com/Chainski/AES-Encoder) , I'm still working on it atm.

> is crypter still working and able to bypass av detection ??

**Comment by kabuchi391** [comment]
Amazing!! You have tutorial on how to develop these projects?

**Comment by kabuchi391** [comment]
I am still learning software development.Mostly game development.
